include:
  - local: .gitlab/build.yml
  - local: .gitlab/docker.yml
  - local: .gitlab/docker/builder/gitlab.yml
  - local: .gitlab/docker/testbed/gitlab.yml
  - local: .gitlab/docker/sdk/gitlab.yml
  - local: .gitlab/testbed.yml
  - local: .gitlab/testbed/netgear-rax40.yml

stages:
  - docker
  - build
  - docker SDK
  - run

build test intel_mips prpl webui:
  extends: .build test config
  variables:
    CI_BUILD_CONFIG_EXTRA: >
      +BUILD_LOG +SDK +PACKAGE_prplmesh-dwpal

run test Netgear RAX40 with system on NAND:
  dependencies:
    - build test intel_mips prpl webui
  extends: .netgear-rax40 testbed
  variables:
    LABGRID_TARGET: "$DUT_BOARD-nand"
    TFTP_IMAGE_FILENAME: NETGEAR_RAX40-squashfs-fullimage.img
