# This is a basic workflow to help you get started with Actions

name: build_prlpwrt

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Prepare environment.
        env:
            DEBIAN_FRONTEND: noninteractive
        run: |
            sudo apt-get update
            sudo apt-get install -y build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libreadline-dev libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint ccache curl wget vim nano python python3 python-pip python3-pip python-ply python3-ply haveged lrzsz device-tree-compiler scons antlr3 gperf ecj fastjar mkisofs

      # Runs a set of commands using the runners shell
      - name: Clone source and install
        run: |
          git clone https://github.com/paldier/prplwrt
          cd prplwrt
          ./scripts/gen_config.py intel_mips prpl webui luci wav500
          cd package/feeds/luci
          ln -sf ../../../feeds/luci/collections/luci ./
          cd ../../../
          rm .config
          cp k3c.config .config
          
      - name: Build
        run: |
          cd prplwrt
          make

